name: flutter_app
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Navigation
  auto_route: ^3.2.0

  #local storage
  path_provider: ^2.0.5

  # widgets
  focused_menu: ^1.0.5
  carousel_slider: ^4.1.1
  salomon_bottom_bar: ^3.3.1

  # images
  camera: ^0.9.4+9
  image: ^3.1.3

  #video
  video_player: ^2.4.2
  chewie: ^1.3.1
  ffmpeg_kit_flutter: ^4.5.1

  #other utils
  permission_handler: ^8.3.0
  glob: ^2.0.2
  intl: ^0.17.0
  awesome_notifications: ^0.6.21
  share_plus: ^4.0.3

  #launch
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  flutter_staggered_grid_view: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #code generation
  build_runner: ^2.1.10
  auto_route_generator: ^3.2.0


flutter_icons:
  android: "launch_icon"
  ios: "launch_icon"
  image_path: "assets/icons/launch_icon.png"

flutter_native_splash:
  color: "#ffffff"
  #  background_image: "assets/background.png"
  image: assets/icons/launch_icon.png

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
